# Generated by Django 5.2.8 on 2025-11-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(help_text='La coordinata di latitudine in formato decimale (float).', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='La coordinata di longitudine in formato decimale (float).', verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='PhotovoltaicSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_power', models.FloatField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('brand', models.CharField(default='NA', max_length=100)),
                ('inclination', models.IntegerField(blank=True, null=True)),
                ('selling_rate_per_kwh', models.FloatField(blank=True, null=True)),
                ('buying_rate_per_kwh', models.FloatField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photovoltaic_system', to='SP.community')),
            ],
        ),
        migrations.CreateModel(
            name='PanelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('lightness', models.FloatField()),
                ('power', models.FloatField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_data', to='SP.photovoltaicsystem', verbose_name='Impianto Fotovoltaico')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CLN', 'Clean Panels'), ('SBT', 'Substitutions of a Panel')], max_length=3, unique=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='SP.photovoltaicsystem', verbose_name='Impianto Fotovoltaico')),
            ],
            options={
                'verbose_name': 'Intervento di Manutenzione',
                'verbose_name_plural': 'Interventi di Manutenzione',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='SP.community')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
