# Generated by Django 5.2.14 on 2026-05-15 16:29

import django.db.models.deletion
from django.db import migrations, models


def create_default_city(apps, schema_editor):
    City = apps.get_model('SP', 'City')
    City.objects.get_or_create(id=1, defaults={'name': 'Default City'})

class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0003_customer_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_city),
        migrations.RemoveField(
            model_name='community',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='community',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='code',
            field=models.CharField(choices=[('CLN', 'Pulizia Pannelli'), ('SBT', 'Sostituzione Pannello'), ('ELC', 'Manutenzione Elettrica e Serraggi'), ('INV', 'Intervento su Inverter'), ('INF', 'Ispezione Termografica/Visiva'), ('STR', 'Controllo Strutture e Ancoraggi'), ('RPL', 'Sostituzione Componenti Minori (Fusibili/Connettori)'), ('OTH', 'Altro')], max_length=3, verbose_name='Tipo di Intervento'),
        ),
        migrations.AddField(
            model_name='community',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='SP.city', verbose_name='Citta'),
            preserve_default=False,
        ),
    ]
