# Generated by Django 5.2.17 on 2026-09-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0004_city_remove_community_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='SP.city', verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='SP.community'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photovoltaic_systems', to='SP.community'),
        ),
    ]
