# Generated by Django 5.2.17 on 2026-09-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0005_coherent_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photovoltaic_systems', to='SP.customer', verbose_name='Proprietario'),
        ),
    ]
