# Generated by Django 5.2.17 on 2026-09-30 14:51

import django.db.models.deletion
from django.db import migrations, models


def assign_owners(apps, schema_editor):
    """Le community esistenti con utenti hanno come titolare il primo utente registrato."""
    Community = apps.get_model("SP", "Community")
    for community in Community.objects.filter(owner__isnull=True):
        community.owner = community.customers.order_by("id").first()
        if community.owner:
            community.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0006_photovoltaicsystem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photovoltaicsystem',
            name='owner',
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owned_community', to='SP.customer', verbose_name='Titolare'),
        ),
        migrations.RunPython(assign_owners, migrations.RunPython.noop),
    ]
