# Generated by Django 5.2.17 on 2026-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0007_community_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data ultimo controllo'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('DRT', 'Pannelli sporchi'), ('FLT', 'Probabile guasto')], default='OK', max_length=3, verbose_name='Stato'),
        ),
    ]
