# Generated by Django 5.2.17 on 2026-10-06 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Min


def remove_duplicate_readings(apps, schema_editor):
    """Prima del vincolo di unicità: delle misure con lo stesso impianto e minuto si tiene la prima."""
    PanelData = apps.get_model('SP', 'PanelData')
    duplicates = (
        PanelData.objects.values('system_id', 'time_stamp')
        .annotate(count=Count('id'), first=Min('id'))
        .filter(count__gt=1)
    )
    for duplicate in duplicates:
        PanelData.objects.filter(system_id=duplicate['system_id'], time_stamp=duplicate['time_stamp']).exclude(
            id=duplicate['first']
        ).delete()


def remove_bridge_user(apps, schema_editor):
    """L'utente "bridge" e il suo token servivano per inviare le misure via HTTP: ora i dispositivi usano MQTT.

    La tabella dei token resta (l'app rest_framework.authtoken non c'è più), ma vuota, così eliminare gli
    utenti non viola le sue chiavi esterne.
    """
    connection = schema_editor.connection
    if 'authtoken_token' in connection.introspection.table_names():
        with connection.cursor() as cursor:
            cursor.execute('DELETE FROM authtoken_token')
    apps.get_model('auth', 'User').objects.filter(username='bridge', is_superuser=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0009_intervention_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data di installazione')),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo messaggio')),
                ('pump_running', models.BooleanField(default=False, verbose_name='Pompa in funzione')),
                ('last_cleaning', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo lavaggio')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivi',
            },
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('DRT', 'Pannelli sporchi'), ('FLT', 'Probabile guasto')], max_length=3, verbose_name='Stato precedente'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data cambiamento di stato'),
        ),
        migrations.RunPython(remove_duplicate_readings, migrations.RunPython.noop),
        migrations.RunPython(remove_bridge_user, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paneldata',
            constraint=models.UniqueConstraint(fields=('system', 'time_stamp'), name='unique_reading_per_minute'),
        ),
        migrations.AddField(
            model_name='device',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_devices', to=settings.AUTH_USER_MODEL, verbose_name='Installato da'),
        ),
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='SP.photovoltaicsystem', verbose_name='Impianto Fotovoltaico'),
        ),
    ]
